name: Python linting

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry install
    - name: Lint with black
      run: |
        python -m poetry run black .\src\ --check
    - name: Lint with isort
      run: |
        python -m poetry run isort .\src\ --diff
    - name: Lint with flake8
      run: |
        python -m poetry run flake8 .\src\ --statistics  
      
